'use strict';
// #before
// #import
// #variable
// #block
// #build
  // run
  export const run=(tyin,els)=>{
    tyin.elementCreate({
      sc_cr_c042:{
        function(){
          tyin.loadPackage_fontAwesomeFree();
          tyin.runObject({
            orientation(){
              const run=()=>{
                tyin.insertStyle('html * { transition: unset !important; }',350/2);
              };
              tyin.listenDOM('add',els.sc_cr_c042,'observe_resize',(data)=>{
                tyin.isPortrait(data.contentRect.width,data.contentRect.height+192,()=>{
                  tyin.elementState(els.sc_cr_c042,'sc_mk_orientation_portrait','sc_mk_orientation_landscape',true);
                  run();
                },()=>{
                  tyin.elementState(els.sc_cr_c042,'sc_mk_orientation_landscape','sc_mk_orientation_portrait',true);
                  run();
                });
              });
            },
            client_ve_page(){
              if(els.client_ve_page&&els.client_ve_page.result){
                tyin.loop(()=>{
                  if(els.sc_cr_c042.sc_bk_block_float){
                    els.sc_cr_c042.sc_bk_block_float.add(els.sc_cr_c042.sc_bk_template_float({
                      control_type:'sc_bk_control_base',
                      control_data:{
                        array:[],
                        title:`${els.client_ve_page.result.title} ${els.client_ve_page.result.data}`
                      },
                      view_type:'sc_bk_view_listText',
                      view_data:[]
                    }));
                    return true;
                  }
                  return false;
                });
              }
            }
          });
          els.sc_cr_c042.load_player=(src,poster=`${els.client_ve_serverURL}/content/asset/image@0.1.0/player/poster.png`,title,description)=>{
            tyin.package_HLS_play('HLS',els.sc_cr_c042_cr_cr_video,src,poster);
            els.sc_cr_c042_cr_player_cr_sync.style.setProperty('background-image',`url(${poster})`);
            els.sc_cr_c042_cr_cr_video.play();
            tyin.elementState(els.sc_cr_c042_cr,'sc_mk_theater','',true);
            tyin.elementState(els.sc_cr_c042_cr_player_cr_cover.children[0],'fa-compress-alt','fa-expand-alt',true);
            setTimeout(()=>{
              els.sc_cr_c042_cr_cr_video.setAttribute('controls','');
            },350*1.25*2);
            els.sc_cr_c042_cr_player_control_info_title.innerHTML=title;
            els.sc_cr_c042_cr_player_control_info_description.innerHTML=description;
          };
          els.sc_cr_c042.load_playlist=()=>{};
          els.sc_cr_c042.sc_bk_control_base=(array=['back','refresh','_title','page','filter','edit','more'],title,insert_element)=>{
            if(array.includes('back')){
              tyin.elementCreate({
                sc_bk_control_base_back:{
                  element:[,,'<i class="fas fa-arrow-left"></i>'],
                  function(){
                    tyin.listenDOM('add',this.element,'pointer_up',()=>{
                      els.sc_cr_c042[els.sc_cr_c042_cr_cr_cr.dataset.current_who].back();
                    },undefined,0);
                  }
                }
              },insert_element);
            }
            if(array.includes('refresh')){
              tyin.elementCreate({
                sc_bk_control_base_refresh:{
                  element:[,,'<i class="fas fa-redo"></i>']
                }
              },insert_element);
            }
            tyin.elementCreate({
              sc_bk_control_base_title:{
                element:[,,`<span class="sc_mk_title">${title}</span><span class="sc_mk_toTop"><span></span><i class="fas fa-arrow-up"></i></span>`],
                function(){
                  tyin.listenDOM('add',this.element,'pointer_up',()=>{
                    if(!this.element.parentElement.parentElement.getAttribute('style')){
                      if(document.documentElement.classList.contains('ic_nr_browser_safari')){
                        this.element.parentElement.nextElementSibling.style.setProperty('overflow','hidden');
                        this.element.parentElement.nextElementSibling.scroll({behavior:'smooth',left:0,top:0});
                        this.element.parentElement.nextElementSibling.style.removeProperty('overflow');
                      }else{
                        this.element.parentElement.nextElementSibling.scroll({behavior:'smooth',left:0,top:0});
                      }
                    }
                  },undefined,0);
                  let position=null;
                  this.element.parentElement.nextElementSibling.addEventListener('scroll',tyin.throttle(()=>{
                    this.element.lastElementChild.children[0].innerHTML=`${(this.element.parentElement.nextElementSibling.scrollTop/(this.element.parentElement.nextElementSibling.scrollHeight-this.element.parentElement.nextElementSibling.offsetHeight)*100).toFixed()}<span>%</span>`;
                    if(this.element.parentElement.nextElementSibling.scrollTop>8){
                      tyin.elementState(this.element.parentElement,'sc_mk_bg','',true);
                    }else{
                      tyin.elementState(this.element.parentElement,'','sc_mk_bg',true);
                    }
                    if(this.element.parentElement.nextElementSibling.scrollTop>0){
                      tyin.elementState(this.element,'sc_mk_displayToTop','',true);
                    }else{
                      tyin.elementState(this.element,'','sc_mk_displayToTop',true);
                    }
                    if(this.element.parentElement.nextElementSibling.scrollTop<=0||this.element.parentElement.nextElementSibling.scrollTop>=this.element.parentElement.nextElementSibling.scrollHeight-this.element.parentElement.nextElementSibling.offsetHeight){
                      tyin.elementState(this.element.parentElement,'','sc_mk_up sc_mk_down',true);
                    }else{
                      if(this.element.parentElement.nextElementSibling.scrollTop<position){
                        tyin.elementState(this.element.parentElement,'sc_mk_up','sc_mk_down',true);
                      }else{
                        tyin.elementState(this.element.parentElement,'sc_mk_down','sc_mk_up',true);
                      }
                    }
                    position=this.element.parentElement.nextElementSibling.scrollTop;
                  }));
                  if(array.includes('back')){
                    let touchStart_clientX=0;
                    let prev_element=null;
                    this.element.addEventListener('touchstart',(event)=>{
                      prev_element=document.querySelectorAll(`.${els.sc_cr_c042_cr_cr_cr.dataset.current_who}_prev`);
                      prev_element=prev_element[prev_element.length-1];
                      if(event.target===this.element){
                        touchStart_clientX=event.changedTouches[0].clientX;
                      }
                    });
                    this.element.addEventListener('touchmove',tyin.throttle((event)=>{
                      if(event.changedTouches[0].clientX>=touchStart_clientX){
                        this.element.classList.remove('ic_active');
                        this.element.parentElement.parentElement.style.setProperty('transition','unset');
                        this.element.parentElement.parentElement.style.setProperty('transform',`translateX(${event.changedTouches[0].clientX-touchStart_clientX}px)`);
                        prev_element.style.setProperty('transition','unset');
                        prev_element.style.setProperty('transform',`translateX(${-this.element.parentElement.offsetWidth*0.25+this.element.parentElement.offsetWidth*0.25*(event.changedTouches[0].clientX-touchStart_clientX)/this.element.parentElement.offsetWidth}px)`);
                      }
                    },1000/120));
                    this.element.addEventListener('touchend',(event)=>{
                      setTimeout(()=>{
                        setTimeout(()=>{
                          if(event.changedTouches[0].clientX-touchStart_clientX>this.element.parentElement.offsetWidth/2){
                            els.sc_cr_c042[els.sc_cr_c042_cr_cr_cr.dataset.current_who].back();
                          }
                        },0);
                        setTimeout(()=>{
                          this.element.parentElement.parentElement.style.removeProperty('transition');
                          this.element.parentElement.parentElement.style.removeProperty('transform');
                          setTimeout(()=>{
                            tyin.removeEmpty(this.element.parentElement.parentElement);
                          },1000/24);
                          prev_element.style.removeProperty('transition');
                          prev_element.style.removeProperty('transform');
                          setTimeout(()=>{
                            tyin.removeEmpty(prev_element);
                          },1000/24);
                          touchStart_clientX=0;
                        },0);
                      },1000/120);
                    });
                  }
                }
              }
            },insert_element);
            if(array.includes('page')){
              tyin.elementCreate({
                sc_bk_control_base_page:{
                  sc_bk_control_base_page_prev:{
                    element:[,,'<i class="fas fa-angle-left"></i>']
                  },
                  sc_bk_control_base_page_current:{
                    element:[,,'2']
                  },
                  sc_bk_control_base_page_next:{
                    element:[,,'<i class="fas fa-angle-right"></i>']
                  }
                }
              },insert_element);
            }
            if(array.includes('filter')){
              tyin.elementCreate({
                sc_bk_control_base_filter:{
                  element:[,,'<i class="fas fa-filter"></i>']
                }
              },insert_element);
            }
            if(array.includes('edit')){
              tyin.elementCreate({
                sc_bk_control_base_edit:{
                  element:[,,'<i class="fas fa-pen"></i>']
                }
              },insert_element);
            }
            if(array.includes('more')){
              tyin.elementCreate({
                sc_bk_control_base_more:{
                  element:[,,'<i class="fas fa-ellipsis-v"></i>']
                }
              },insert_element);
            }
          };
          els.sc_cr_c042.sc_bk_view_listIndex=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_view_listText=(data,insert_element)=>{
            tyin.for(data,(...data)=>{
              tyin.elementCreate({
                sc_bk_view_listText_block:{
                  function(){
                    if(data[2].title){
                      tyin.elementCreate({
                        sc_bk_view_listText_mk_description:{
                          element:[,,data[2].title]
                        }
                      },this.element,'afterbegin');
                    }
                    if(data[2].description){
                      tyin.elementCreate({
                        sc_bk_view_listText_mk_description:{
                          element:[,,data[2].description]
                        }
                      },this.element,'beforeend');
                    }
                  },
                  sc_bk_view_listText_block_content:{
                    function(){
                      tyin.for(data[2].content,(...data)=>{
                        tyin.elementCreate([
                          {
                            function(elements,element){
                              if(data[2].function){
                                data[2].function.call(this,elements,element);
                              }
                              tyin.elementCreate([
                                {
                                  element:['span',{class:'sc_mk_left'},data[2].icon]
                                }
                              ],this.element);
                              if(data[2].content){
                                tyin.elementCreate([
                                  {
                                    element:['span',{class:'sc_mk_content'},data[2].content],
                                    function(){
                                      if(data[2].description){
                                        tyin.elementCreate([
                                          {
                                            element:['span',{class:'sc_bk_view_listText_mk_description'},data[2].description]
                                          }
                                        ],this.element);
                                      }
                                    }
                                  }
                                ],this.element);
                              }
                              if(data[2].button){
                                tyin.elementCreate([
                                  {
                                    element:['span',{class:'sc_mk_right'},data[2].button]
                                  }
                                ],this.element);
                              }
                            }
                          }
                        ],this.element);
                      },0);
                    }
                  }
                }
              },insert_element);
            },0);
          };
          els.sc_cr_c042.sc_bk_view_listImage=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_view_contentVideo=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_view_contentPlaylist=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_view_contentForum=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_view_otherComment=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_view_otherEdit=(data,insert_element)=>{};
          els.sc_cr_c042.sc_bk_template_float=(data,record,callback=()=>{})=>{
            if(!els.sc_cr_c042.sc_bk_template_float.record){
              els.sc_cr_c042.sc_bk_template_float.record=[];
            }
            let record_state=false;
            if(record){
              tyin.for(els.sc_cr_c042.sc_bk_template_float.record,(...data)=>{
                if(data[2]===record){
                  record_state=true;
                }
              },0);
            }
            if(!record_state){
              if(record&&!els.sc_cr_c042.sc_bk_template_float.record.includes(record)){
                tyin.debug(()=>{
                  console.log('++++ sc_cr_c042.sc_bk_template_float.record:',record);
                });
                els.sc_cr_c042.sc_bk_template_float.record.push(record);
              }
              const result=tyin.elementCreate({
                '':{
                  function(){
                    tyin.listenDOM('add',this.element,'pointer_up',(data)=>{
                      if(data.target===this.element&&data.target.classList.contains('ic_active')){
                        els.sc_cr_c042.sc_bk_block_float.back();
                      }
                    },undefined,0);
                  },
                  sc_bk_block_f_box:{
                    [`sc_bk_block_f_box_control ${data.control_type}`]:{
                      function(){
                        els.sc_cr_c042[data.control_type](data.control_data.array,data.control_data.title,this.element);
                      }
                    },
                    sc_bk_block_f_box_view:{
                      [data.view_type]:{
                        function(){
                          els.sc_cr_c042[data.view_type](data.view_data,this.element);
                        }
                      }
                    }
                  },
                  sc_bk_block_f_back:{
                    element:[,,'<i class="fas fa-times-circle"></i>']
                  }
                }
              });
              callback(result);
              return result[''];
            }
          };
          els.sc_cr_c042.sc_bk_template_solid=(data,record,callback=()=>{})=>{
            if(!els.sc_cr_c042.sc_bk_template_solid.record){
              els.sc_cr_c042.sc_bk_template_solid.record=[];
            }
            let record_state=false;
            if(record){
              tyin.for(els.sc_cr_c042.sc_bk_template_solid.record,(...data)=>{
                if(data[2]===record){
                  record_state=true;
                }
              },0);
            }
            if(!record_state){
              if(record&&!els.sc_cr_c042.sc_bk_template_solid.record.includes(record)){
                tyin.debug(()=>{
                  console.log('++++ sc_cr_c042.sc_bk_template_solid.record:',record);
                });
                els.sc_cr_c042.sc_bk_template_solid.record.push(record);
              }
              const result=tyin.elementCreate({
                '':{
                  [`sc_bk_block_s_control ${data.control_type}`]:{
                    function(){
                      els.sc_cr_c042[data.control_type](data.control_data.array,data.control_data.title,this.element);
                    }
                  },
                  sc_bk_block_s_view:{
                    [data.view_type]:{
                      function(){
                        els.sc_cr_c042[data.view_type](data.view_data,this.element);
                      }
                    }
                  }
                }
              });
              callback(result);
              return result[''];
            }
          };
          els.sc_cr_c042.sc_bk_block_float=tyin.elementBlock(els.sc_cr_c042,'sc_bk_block_float','afterbegin',350*1.25);
          els.sc_cr_c042.sc_bk_block_solid_video=tyin.elementBlock(els.sc_cr_c042_cr_cr_cr_video,'sc_bk_block_solid_video',undefined,350*1.25);
          els.sc_cr_c042.sc_bk_block_solid_video.add(els.sc_cr_c042.sc_bk_template_solid({
            control_type:'sc_bk_control_base',
            control_data:{
              array:[],
              title:'视频'
            },
            view_type:'sc_bk_view_listText',
            view_data:[
              {
                title:'',
                content:[
                  {
                    icon:'<i class="fas fa-circle-notch" style="color: var(--ic_ve_color_system_blue);"></i>',
                    content:'电视台',
                    button:'<i class="fas fa-chevron-right"></i>',
                    description:'限 iPhoneOS 与 iPadOS 和 macOS Safari.',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_video.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'电视台'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element,async(data)=>{
                          tyin.elementState(data.sc_bk_view_listText,'ic_bk_progressIndicatorCircular_indeterminate_24','',true);
                          const container=data.sc_bk_view_listText.children[0].children[0];
                          await tyin.fetch(`${els.client_ve_serverURL}/s100/video/tvLive`,'GET',undefined,undefined,undefined,'json',(data_)=>{
                            let html='';
                            if(data_.result){
                              tyin.for(data_.result,(...data)=>{
                                html+=`<div><span class="sc_mk_left"></span><span class="sc_mk_content" data-live_url="${data[2].url}" data-live_name="${data[2].name}" data-live_logo="${data[2].logo}">${data[2].name}</span></div>`;
                              },0);
                              container.innerHTML=html;
                              tyin.listenDOM('add',data.sc_bk_view_listText,'pointer_up',(data)=>{
                                const target=data.target.lastElementChild;
                                if(target.dataset.live_url){
                                  els.sc_cr_c042.load_player(target.dataset.live_url,target.dataset.live_logo,target.dataset.live_name,'电视台');
                                }
                              },undefined,0);
                            }else{
                              container.innerHTML='未能获取数据';
                            }
                          });
                          tyin.elementState(data.sc_bk_view_listText,'','ic_bk_progressIndicatorCircular_indeterminate_24',true);
                        }),this.element);
                      },undefined,0,true);
                    }
                  },
                  {
                    icon:'',
                    content:'电影',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_video.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'电影'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0,true);
                    }
                  },
                  {
                    icon:'',
                    content:'电视剧',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_video.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'电视剧'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0,true);
                    }
                  },
                  {
                    icon:'',
                    content:'动画剧',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_video.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'动画剧'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0,true);
                    }
                  }
                ],
                description:`c042 已停止编写, <a href="${location.search?location.search.replace('&version=c042','').replace('version=c042','')+'&version=c043'.replace('?&','?'):'?version=c043'}" style="color: var(--ic_ve_color_system_blue);">点此访问 c043</a>.`
              }
            ]
          },els.sc_cr_c042_cr_menu_video),els.sc_cr_c042_cr_menu_video);
          els.sc_cr_c042.sc_bk_block_solid_interactive=tyin.elementBlock(els.sc_cr_c042_cr_cr_cr_interactive,'sc_bk_block_solid_interactive',undefined,350*1.25);
          els.sc_cr_c042.sc_bk_block_solid_interactive.add(els.sc_cr_c042.sc_bk_template_solid({
            control_type:'sc_bk_control_base',
            control_data:{
              array:[],
              title:'互动'
            },
            view_type:'sc_bk_view_listText',
            view_data:[
              {
                title:'',
                content:[
                  {
                    icon:'',
                    content:'点评',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_interactive.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'点评'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'播单',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_interactive.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'播单'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'话题',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_interactive.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'话题'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              }
            ]
          },els.sc_cr_c042_cr_menu_interactive),els.sc_cr_c042_cr_menu_interactive);
          els.sc_cr_c042.sc_bk_block_solid_account=tyin.elementBlock(els.sc_cr_c042_cr_cr_cr_account,'sc_bk_block_solid_account',undefined,350*1.25);
          els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
            control_type:'sc_bk_control_base',
            control_data:{
              array:[],
              title:'账户'
            },
            view_type:'sc_bk_view_listText',
            view_data:[
              {
                title:'记录',
                content:[
                  {
                    icon:'',
                    content:'视频',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'视频'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'点评',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'点评'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'播单',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'播单'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'话题',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'话题'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'搜寻',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'搜寻'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'标记',
                content:[
                  {
                    icon:'',
                    content:'电视台',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'电视台'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'电影',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'电影'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'电视剧',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'电视剧'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'动画剧',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'动画剧'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'播单',
                content:[
                  {
                    icon:'',
                    content:'创建',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'创建'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'收纳',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'收纳'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'话题',
                content:[
                  {
                    icon:'',
                    content:'创建',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'创建'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'收纳',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'收纳'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'参与',
                content:[
                  {
                    icon:'',
                    content:'弹幕',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'弹幕'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'点评',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'点评'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'播单',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'播单'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'话题',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'话题'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'账户',
                content:[
                  {
                    icon:'',
                    content:'登入',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'登入'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'注册',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'注册'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'编辑',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'编辑'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'登出',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'登出'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'偏好',
                content:[
                  {
                    icon:'',
                    content:'通用',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'通用'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'通知',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'通知'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'播放机',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'播放机'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'搜寻',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'搜寻'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'其它',
                content:[
                  {
                    icon:'',
                    content:'手册',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'手册'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'<i class="fas fa-circle-notch" style="color: var(--ic_ve_color_system_blue);"></i>',
                    content:'工坊',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'工坊'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[
                                {
                                  icon:'<i class="fab fa-whmcs"></i>',
                                  content:'调试',
                                  button:'<i class="fas fa-chevron-right"></i>',
                                  description:'作者的快捷键.',
                                  function(){
                                    tyin.listenDOM('add',this.element,'pointer_up',()=>{
                                      els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                                        control_type:'sc_bk_control_base',
                                        control_data:{
                                          array:['back'],
                                          title:'调试'
                                        },
                                        view_type:'sc_bk_view_listText',
                                        view_data:[
                                          {
                                            title:'播放机',
                                            content:[
                                              {
                                                icon:'',
                                                content:'装载一个视频流',
                                                button:'',
                                                function(){
                                                  tyin.listenDOM('add',this.element,'pointer_up',()=>{
                                                    els.sc_cr_c042.load_player('https://56.com-t-56.com/20190728/23849_9b8076fd/index.m3u8','https://images.cnblogsc.com/pic/upload/vod/2019-04/201904241556071910.jpg','复仇者联盟4','安东尼·罗素, 乔·罗素');
                                                  },undefined,0);
                                                }
                                              },
                                              {
                                                icon:'',
                                                content:'装载一个直播流',
                                                button:'',
                                                function(){
                                                  tyin.listenDOM('add',this.element,'pointer_up',()=>{
                                                    els.sc_cr_c042.load_player('http://ivi.bupt.edu.cn/hls/cctv10.m3u8','','CCTV-10','普通');
                                                  },undefined,0);
                                                }
                                              },
                                              {
                                                icon:'',
                                                content:'<input placeholder="装载 m3u8 url">',
                                                button:'',
                                                function(){
                                                  this.element.addEventListener('input',(event)=>{
                                                    els.sc_cr_c042.load_player(event.target.value,'','url m3u8',event.target.value);
                                                  });
                                                }
                                              }
                                            ]
                                          },
                                          {
                                            title:'其它',
                                            content:[
                                              {
                                                icon:'',
                                                content:'Navigator',
                                                button:'<i class="fas fa-chevron-right"></i>',
                                                function(){
                                                  tyin.listenDOM('add',this.element,'pointer_up',()=>{
                                                    els.sc_cr_c042.sc_bk_block_solid_account.add(els.sc_cr_c042.sc_bk_template_solid({
                                                      control_type:'sc_bk_control_base',
                                                      control_data:{
                                                        array:['back'],
                                                        title:'Navigator'
                                                      },
                                                      view_type:'sc_bk_view_listText',
                                                      view_data:[
                                                        {
                                                          title:'languages',
                                                          content:[
                                                            {
                                                              icon:'',
                                                              content:navigator.languages.toString().replace(/,/g,',\n'),
                                                              button:''
                                                            }
                                                          ]
                                                        },
                                                        {
                                                          title:'userAgent',
                                                          content:[
                                                            {
                                                              icon:'',
                                                              content:navigator.userAgent,
                                                              button:''
                                                            }
                                                          ]
                                                        },
                                                        {
                                                          title:'lyin',
                                                          content:[
                                                            {
                                                              icon:'',
                                                              content:document.documentElement.classList.value.replace(/\s/g,',\n'),
                                                              button:''
                                                            }
                                                          ],
                                                          description:'若产生变化, 重新进入 Navigator 刷新数据.'
                                                        }
                                                      ]
                                                    }));
                                                  },undefined,0);
                                                }
                                              },
                                              {
                                                icon:'',
                                                content:'<input type="number" min="0" max="100" placeholder="上方距离">',
                                                button:'',
                                                function(){
                                                  this.element.addEventListener('input',(event)=>{
                                                    event.target.setAttribute('max',els.sc_cr_c042.offsetHeight/2);
                                                    if(event.target.value>parseInt(event.target.max)){
                                                      event.target.value=parseInt(event.target.max);
                                                    }
                                                    els.sc_cr_c042.style.setProperty('border-top-width',`${event.target.value?event.target.value:0}px`);
                                                    els.sc_cr_c042.style.setProperty('overflow','unset');
                                                    setTimeout(()=>{
                                                      els.sc_cr_c042.style.removeProperty('overflow');
                                                    },350*1.25);
                                                  });
                                                }
                                              },
                                              {
                                                icon:'',
                                                content:'新的标签',
                                                button:'',
                                                description:'这个标签可能没有后退按钮.',
                                                function(){
                                                  tyin.listenDOM('add',this.element,'pointer_up',()=>{
                                                    tyin.openTab(`${location.origin+location.pathname}?version=c042`);
                                                  },undefined,0);
                                                }
                                              },
                                              {
                                                icon:'',
                                                content:'新的窗口',
                                                button:'',
                                                description:'尽量少显示外部 GUI 构成.',
                                                function(){
                                                  tyin.listenDOM('add',this.element,'pointer_up',()=>{
                                                    tyin.openWindow(`${location.origin+location.pathname}?version=c042`);
                                                  },undefined,0);
                                                }
                                              },
                                              {
                                                icon:'',
                                                content:'此次启动探测',
                                                button:'',
                                                description:'...',
                                                function(){
                                                  tyin.loop(()=>{
                                                    if(this.element.children[1]&&this.element.children[1].children[0]){
                                                      const description=this.element.children[1].children[0];
                                                      description.innerHTML='';
                                                      if(beforeListResult){
                                                        for(const key in beforeListResult){
                                                          description.innerHTML+=`${beforeListResult[key]} ${key}ms\n`;
                                                        }
                                                        description.innerHTML=description.innerHTML.trim();
                                                      }else{
                                                        tyin.removeElement(this.element);
                                                      }
                                                      return true;
                                                    }
                                                    return false;
                                                  });
                                                }
                                              }
                                            ]
                                          }
                                        ]
                                      },this.element),this.element);
                                    },undefined,0);
                                  }
                                }
                              ]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              }
            ]
          },els.sc_cr_c042_cr_menu_account),els.sc_cr_c042_cr_menu_account);
          els.sc_cr_c042.sc_bk_block_solid_search=tyin.elementBlock(els.sc_cr_c042_cr_cr_cr_search,'sc_bk_block_solid_search',undefined,350*1.25);
          els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
            control_type:'sc_bk_control_base',
            control_data:{
              array:[],
              title:'搜寻'
            },
            view_type:'sc_bk_view_listText',
            view_data:[
              {
                title:'搜寻',
                content:[
                  {
                    icon:'',
                    content:'综合',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'综合'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'视频',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'视频'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'播单',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'播单'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  },
                  {
                    icon:'',
                    content:'话题',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
                          control_type:'sc_bk_control_base',
                          control_data:{
                            array:['back'],
                            title:'话题'
                          },
                          view_type:'sc_bk_view_listText',
                          view_data:[
                            {
                              title:'',
                              content:[]
                            }
                          ]
                        },this.element),this.element);
                      },undefined,0);
                    }
                  }
                ]
              },
              {
                title:'',
                content:[
                  {
                    icon:'<i class="fas fa-search"></i>',
                    content:'<input enterkeyhint="search" type="search" placeholder="搜寻">',
                    button:'<i class="fas fa-chevron-right"></i>'
                  }
                ]
              },
              {
                title:'直搜',
                content:[
                  {
                    icon:'<i class="fas fa-circle-notch" style="color: var(--ic_ve_color_system_blue);"></i>',
                    content:'<input enterkeyhint="search" type="search" placeholder="直搜">',
                    button:'<i class="fas fa-chevron-right"></i>',
                    function(){
                      let input=null;
                      tyin.listenDOM('add',this.element,'pointer_up',()=>{
                        input.focus();
                      },undefined,0);
                      tyin.loop(()=>{
                        if(this.element.children[1]&&this.element.children[1].children[0]){
                          input=this.element.children[1].children[0];
                          input.addEventListener('keydown',async(event)=>{
                            if(event.key==='Enter'){
                              if(input.value.trim()!==''){
                                els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
                                  control_type:'sc_bk_control_base',
                                  control_data:{
                                    array:['back'],
                                    title:`"${input.value}"`
                                  },
                                  view_type:'sc_bk_view_listText',
                                  view_data:[
                                    {
                                      title:'',
                                      content:[]
                                    }
                                  ]
                                },undefined,async(data)=>{
                                  tyin.elementState(data.sc_bk_view_listText,'ic_bk_progressIndicatorCircular_indeterminate_24','',true);
                                  const container=data.sc_bk_view_listText.children[0].children[0];
                                  await tyin.fetch(`${els.client_ve_serverURL}/s100/video/source`,'GET',undefined,undefined,undefined,'json',(data)=>{
                                    let html='';
                                    tyin.for(data.result,(...data)=>{
                                      if(data[2].url){
                                        html+=`<div style="order:-${data[2].year};"><span class="sc_mk_left"></span><span class="sc_mk_content" data-source_url="${data[2].url}" data-source_name="${data[2].name}" data-source_poster="${data[2].poster}" data-source_year="${data[2].year}">${data[2].name}<span class="sc_bk_view_listText_mk_description">${data[2].year}年, ${data[2].url.toString().split(',').length}话</span></span><span class="sc_mk_right"><i class="fas fa-chevron-right"></i></span></div>`;
                                      }
                                    },0);
                                    container.innerHTML=html;
                                    tyin.listenDOM('add',container,'pointer_up',(data)=>{
                                      const target=data.target.children[1];
                                      if(target.dataset.source_url){
                                        els.sc_cr_c042.sc_bk_block_solid_search.add(els.sc_cr_c042.sc_bk_template_solid({
                                          control_type:'sc_bk_control_base',
                                          control_data:{
                                            array:['back'],
                                            title:target.dataset.source_name
                                          },
                                          view_type:'sc_bk_view_listText',
                                          view_data:[
                                            {
                                              title:'',
                                              content:[]
                                            }
                                          ]
                                        },undefined,(data)=>{
                                          tyin.elementState(data.sc_bk_view_listText,'ic_bk_progressIndicatorCircular_indeterminate_24','',true);
                                          const container=data.sc_bk_view_listText.children[0].children[0];
                                          let html='';
                                          tyin.for(target.dataset.source_url.split(','),(...data)=>{
                                            html+=`<div><span class="sc_mk_left"></span><span class="sc_mk_content" data-source_url="${data[2]}" data-source_name="${target.dataset.source_name}" data-source_poster="${target.dataset.source_poster}" data-source_count="${data[0]+1}">第 ${data[0]+1} 话</span></div>`;
                                          },0);
                                          container.innerHTML=html;
                                          tyin.listenDOM('add',container,'pointer_up',(data)=>{
                                            const target=data.target.lastElementChild;
                                            els.sc_cr_c042.load_player(target.dataset.source_url,target.dataset.source_poster,target.dataset.source_name,`第 ${target.dataset.source_count} 话`);
                                          });
                                          tyin.elementState(data.sc_bk_view_listText,'','ic_bk_progressIndicatorCircular_indeterminate_24',true);
                                        }));
                                      }
                                    },undefined,0);
                                  });
                                  tyin.elementState(data.sc_bk_view_listText,'','ic_bk_progressIndicatorCircular_indeterminate_24',true);
                                }));
                              }
                            }
                          });
                          return true;
                        }
                        return false;
                      });
                    }
                  }
                ]
              }
            ]
          },els.sc_cr_c042_cr_menu_search),els.sc_cr_c042_cr_menu_search);
        },
        sc_cr_c042_cr:{
          sc_cr_c042_cr_menu:{
            function(){
              const set=(data,current_who)=>{
                for(let item=0,length=els.sc_cr_c042_cr_menu.childElementCount;item<length;item++){
                  if(els.sc_cr_c042_cr_menu.children[item]!==data&&els.sc_cr_c042_cr_menu.children[item]!==data.parentElement.parentElement){
                    tyin.elementState(els.sc_cr_c042_cr_menu.children[item],'','sc_mk_open',true);
                  }
                }
                setTimeout(()=>{
                  switch(data.localName){
                    case'div':
                      {
                        tyin.elementState(data,'sc_mk_open','',true);
                      }
                      break;
                    case'input':
                      {
                        tyin.elementState(data.parentElement.parentElement,'sc_mk_open','',true);
                      }
                      break;
                    default:
                      break;
                  }
                },0);
                els.sc_cr_c042_cr_cr_cr.setAttribute('data-current_who',current_who);
              };
              tyin.listenDOM('add',els.sc_cr_c042_cr_menu,'pointer_up',(data)=>{
                switch(data.target){
                  case els.sc_cr_c042_cr_menu_video:
                    {
                      set(data.target,'sc_bk_block_solid_video');
                    }
                    break;
                  case els.sc_cr_c042_cr_menu_interactive:
                    {
                      set(data.target,'sc_bk_block_solid_interactive');
                    }
                    break;
                  case els.sc_cr_c042_cr_menu_account:
                    {
                      set(data.target,'sc_bk_block_solid_account');
                    }
                    break;
                  case els.sc_cr_c042_cr_menu_search:
                    {
                      set(data.target,'sc_bk_block_solid_search');
                    }
                    break;
                  case els.sc_cr_c042_cr_menu_search_form_input:
                    {
                      set(data.target,'sc_bk_block_solid_search');
                    }
                    break;
                  default:
                    break;
                }
              },undefined,0);
              els.sc_cr_c042_cr_menu_search_form_input.addEventListener('pointerdown',(event)=>{
                set(event.target,'sc_mk_search','sc_bk_block_solid_search');
              });
            },
            sc_cr_c042_cr_menu_video:{
              element:[,{class:'sc_mk_open'},'<i class="fas fa-layer-group"></i>'],
              sc_cr_c042_cr_menu_video_title:{
                element:['span',,'视频']
              },
              sc_cr_c042_cr_menu_video_number:{
                element:['span']
              }
            },
            sc_cr_c042_cr_menu_interactive:{
              element:[,,'<i class="fas fa-comments"></i>'],
              sc_cr_c042_cr_menu_interactive_title:{
                element:['span',,'互动']
              },
              sc_cr_c042_cr_menu_interactive_number:{
                element:['span']
              }
            },
            sc_cr_c042_cr_menu_account:{
              element:[,,'<i class="fas fa-user-cog"></i>'],
              sc_cr_c042_cr_menu_account_title:{
                element:['span',,'账户']
              },
              sc_cr_c042_cr_menu_account_number:{
                element:['span',,'9']
              }
            },
            sc_cr_c042_cr_menu_search:{
              element:[,,'<i class="fas fa-search"></i>'],
              function(){
                if(!document.documentElement.classList.contains('ic_nr_platform_mobile')&&getComputedStyle(els.sc_cr_c042_cr_menu_search_form).display!=='none'){
                  tyin.listenDOM('add',els.sc_cr_c042_cr_menu_search,'pointer_up',(data)=>{
                    if(data.target===els.sc_cr_c042_cr_menu_search){
                      els.sc_cr_c042_cr_menu_search_form_input.focus();
                      els.sc_cr_c042_cr_menu_search_form_input.selectionStart=els.sc_cr_c042_cr_menu_search_form_input.selectionEnd=els.sc_cr_c042_cr_menu_search_form_input.value.length;
                    }
                  },undefined,0);
                }
              },
              sc_cr_c042_cr_menu_search_form:{
                sc_cr_c042_cr_menu_search_form_input:{
                  element:['input',{enterkeyhint:'search',type:'search',placeholder:'搜寻'}]
                },
                sc_cr_c042_cr_menu_search_form_clear:{
                  element:['span',,'<i class="fas fa-times-circle"></i>'],
                  function(){
                    tyin.listenDOM('add',els.sc_cr_c042_cr_menu_search_form_clear,'pointer_up',()=>{
                      els.sc_cr_c042_cr_menu_search_form_input.value='';
                      els.sc_cr_c042_cr_menu_search_form_input.focus();
                    },undefined,0);
                  }
                }
              },
              sc_cr_c042_cr_menu_search_title:{
                element:['span',,'搜寻']
              },
              sc_cr_c042_cr_menu_search_number:{
                element:['span']
              }
            },
            sc_cr_c042_cr_menu_font:{
              element:[,,'<i class="fas fa-font"></i>'],
              function(){
                tyin.listenDOM('add',this.element,'pointer_up',async()=>{
                  tyin.elementState(this.element,'sc_mk_disabled','',true);
                  tyin.elementState(this.element,'ic_bk_progressIndicatorCircular_indeterminate_24','',true);
                  await els.client_bk_font_pingFang(els.sc_cr_c042);
                  tyin.elementState(this.element,'','ic_bk_progressIndicatorCircular_indeterminate_24',true);
                  tyin.removeElement(this.element);
                },undefined,0);
                if(document.documentElement.classList.contains('ic_nr_system_brand_apple')){
                  tyin.removeElement(this.element);
                }
              },
              sc_cr_c042_cr_menu_font_title:{
                element:['span',,'苹方']
              },
              sc_cr_c042_cr_menu_font_number:{
                element:['span']
              }
            }
          },
          sc_cr_c042_cr_cr:{
            sc_cr_c042_cr_cr_player:{
              sc_cr_c042_cr_player_cr:{
                sc_cr_c042_cr_player_cr_cover:{
                  element:[,,'<i class="fas fa-expand-alt"></i>'],
                  function(){
                    tyin.listenDOM('add',els.sc_cr_c042_cr_player_cr_cover,'pointer_up',()=>{
                      tyin.elementState(els.sc_cr_c042_cr,'sc_mk_theater','');
                      tyin.elementState(els.sc_cr_c042_cr_player_cr_cover.children[0],'fa-compress-alt','fa-expand-alt');
                      setTimeout(()=>{
                        if(els.sc_cr_c042_cr.classList.contains('sc_mk_theater')&&els.sc_cr_c042_cr_cr_video.getAttribute('src')){
                          els.sc_cr_c042_cr_cr_video.setAttribute('controls','');
                        }else{
                          els.sc_cr_c042_cr_cr_video.removeAttribute('controls');
                        }
                      },350*1.25*2);
                    },undefined,0);
                  }
                },
                sc_cr_c042_cr_player_cr_sync:{
                  element:['canvas'],
                  function(){
                    let async_context=els.sc_cr_c042_cr_player_cr_sync.getContext('2d');
                    els.sc_cr_c042_cr_cr_video.addEventListener('play',()=>{
                      if(els.sc_cr_c042_cr_cr_video.paused){
                        return false;
                      }
                      draw();
                    });
                    let draw=()=>{
                      if(!els.sc_cr_c042_cr.classList.contains('sc_mk_theater')){
                        els.sc_cr_c042_cr_player_cr_sync.setAttribute('width',els.sc_cr_c042_cr_cr_video.clientWidth);
                        els.sc_cr_c042_cr_player_cr_sync.setAttribute('height',els.sc_cr_c042_cr_cr_video.clientHeight);
                        els.sc_cr_c042_cr_player_cr_sync.style.setProperty('width',`${els.sc_cr_c042_cr_cr_video.videoWidth/els.sc_cr_c042_cr_cr_video.videoHeight*54}px`);
                        async_context.drawImage(els.sc_cr_c042_cr_cr_video,0,0,els.sc_cr_c042_cr_cr_video.clientWidth,els.sc_cr_c042_cr_cr_video.clientHeight);
                      }
                      setTimeout(draw,1000/24);
                    };
                  }
                }
              },
              sc_cr_c042_cr_player_control:{
                sc_cr_c042_cr_player_control_info:{
                  function(){
                    tyin.listenDOM('add',els.sc_cr_c042_cr_player_control_info,'pointer_up',(data)=>{
                      els.sc_cr_c042.sc_bk_block_float.add(els.sc_cr_c042.sc_bk_template_float({
                        control_type:'sc_bk_control_base',
                        control_data:{
                          array:[],
                          title:'info'
                        },
                        view_type:'sc_bk_view_listText',
                        view_data:[]
                      }));
                    },undefined,0);
                  },
                  sc_cr_c042_cr_player_control_info_title:{
                    element:[,,'c042']
                  },
                  sc_cr_c042_cr_player_control_info_description:{
                    element:[,,'当前 "搜寻 - 直搜" 与 "视频 - 电视台" 部分可用.']
                  }
                },
                sc_cr_c042_cr_player_control_play:{
                  element:[,,'<i class="fas fa-play"></i>'],
                  function(){
                    const set_button_state=()=>{
                      if(!els.sc_cr_c042_cr_cr_video.getAttribute('src')){
                        tyin.elementState(els.sc_cr_c042_cr_player_control_play,'sc_mk_disabled','',true);
                      }else{
                        tyin.elementState(els.sc_cr_c042_cr_player_control_play,'','sc_mk_disabled',true);
                      }
                    };
                    set_button_state();
                    tyin.listenDOM('add',els.sc_cr_c042_cr_cr_video,'observe_mutation',set_button_state,{attributes:true,attributeFilter:['src']});
                    const set_icon=()=>{
                      if(els.sc_cr_c042_cr_cr_video.paused){
                        tyin.elementState(els.sc_cr_c042_cr_player_control_play.children[0],'fa-play','fa-pause',true);
                      }else{
                        tyin.elementState(els.sc_cr_c042_cr_player_control_play.children[0],'fa-pause','fa-play',true);
                      }
                    };
                    set_icon();
                    tyin.listenDOM('add',els.sc_cr_c042_cr_player_control_play,'pointer_up',()=>{
                      if(els.sc_cr_c042_cr_cr_video.paused){
                        els.sc_cr_c042_cr_cr_video.play();
                      }else{
                        els.sc_cr_c042_cr_cr_video.pause();
                      }
                      set_icon();
                    },undefined,0);
                    els.sc_cr_c042_cr_cr_video.addEventListener('play',()=>{
                      set_icon();
                    });
                    els.sc_cr_c042_cr_cr_video.addEventListener('pause',()=>{
                      set_icon();
                    });
                  }
                },
                sc_cr_c042_cr_player_control_next:{
                  element:[,{class:'sc_mk_disabled'},'<i class="fas fa-step-forward"></i>']
                },
                sc_cr_c042_cr_player_control_playlist:{
                  element:[,,'<i class="fas fa-list"></i>'],
                  function(){
                    tyin.listenDOM('add',els.sc_cr_c042_cr_player_control_playlist,'pointer_up',(data)=>{
                      els.sc_cr_c042.sc_bk_block_float.add(els.sc_cr_c042.sc_bk_template_float({
                        control_type:'sc_bk_control_base',
                        control_data:{
                          array:[],
                          title:'playlist'
                        },
                        view_type:'sc_bk_view_listText',
                        view_data:[]
                      },data.target),els.sc_cr_c042_cr_player_control_playlist);
                    },undefined,0);
                  }
                }
              }
            },
            sc_cr_c042_cr_cr_video:{
              element:['video',{src:'',poster:`${els.client_ve_serverURL}/content/asset/image@0.1.0/player/poster.png`,playsinline:'',preload:'metadata'}]
            },
            sc_cr_c042_cr_cr_cr:{
              element:[,{'data-current_who':'sc_bk_block_solid_video'}],
              sc_cr_c042_cr_cr_cr_video:{},
              sc_cr_c042_cr_cr_cr_interactive:{},
              sc_cr_c042_cr_cr_cr_account:{},
              sc_cr_c042_cr_cr_cr_search:{}
            }
          }
        }
      }
    },els.sc_cr,'beforeend',els);
  };
// #debug
// #after